### ISSUE TITLE
Health bar - level show issue

### ISSUE THREAD

**Issue by yah467958** [Luxocracy/NeatPlates#176]
Hello fellas!
I don't know if it's a bug or no, but lately neat plates show level of the characters even if that option is unmarked, and to be honest its very annoying. Any solutions?

**Comment by Luxocracy** [comment]
Not sure if this is what you might be having an issue with, but in a recent update _subtext_ was added as an option to the regular bar mode. And in the _subtext_ dropdown list there are some options that include the ability to show level.
So if the level is located underneath the name but, usually, above the nameplate it would be from that option. 

If this isn't the case I would need more information on how to reproduce this issue and which theme and version of WoW this is happening on.

**Comment by yah467958** [comment]
Unfortunately it isn't it :(
[https://imgur.com/a/sUyubk8](url)

Theme it's neon

**Comment by Luxocracy** [comment]
Hmm.. That is definitely the subtext that I mentioned before, but I'm not able to reproduce this on my end no matter what I try.

Have you tried setting the value to something other than none and then changing it back? And that the profile that you are checking this in is the one that is currently used by your character?

**Comment by yah467958** [comment]
Yes I tried that, also I re-uninstalled add-on and still nothing.

Nope, I using healer profile as well so I don't think it's profile fault + it's same on another characters. 

Maybe I just should reroll to old version?

**Comment by Luxocracy** [comment]
Could you possibly link me or post the contents of your _NeatPlatesHub.lua_ file located in 'World of Warcraft/_retail/WTF/Account/**accountID**/SavedVariables' so I can completely rule out it being related to the settings in anyway.

**Comment by yah467958** [comment]
Here it is:


NeatPlatesHubSettings = {
	["HubPanelProfileHealer"] = {
		["TextShowOnlyOnActive"] = false,
		["WidgetAuraSort"] = 1,
		["TextShowOnlyOnTargets"] = false,
		["ColorFriendlyBarMode"] = 1,
		["FrameBarWidth"] = 1,
		["UnitSpotlightLookup"] = {
		},
		["EnableOffTankHighlight"] = false,
		["BorderBuffEnrage"] = 1,
		["OpacityFilterNonElite"] = false,
		["Theme"] = "Neon",
		["SpellCastEnableFriendly"] = false,
		["WidgetPandemic"] = false,
		["OpacityFilterPlayers"] = false,
		["StyleEnemyBarsInstanceMode"] = false,
		["ColorFriendlyStatusTextMode"] = 1,
		["HighlightMouseoverScale"] = {
			["y"] = 1,
			["x"] = 1,
			["offset"] = {
				["y"] = 0,
				["x"] = 0,
			},
		},
		["ColorTarget"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0.4313715994358063,
			["g"] = 0.4313715994358063,
			["r"] = 0.4313715994358063,
		},
		["ColorEnemyStatusTextMode"] = 1,
		["WidgetRangeMode"] = 1,
		["OpacityNonTarget"] = 0.7,
		["EmphasizedSlots"] = 1,
		["FilterScaleLock"] = true,
		["StyleEnemyBarsOnElite"] = false,
		["StyleEnemyBarsNoTotem"] = false,
		["IntCastWhoEnable"] = true,
		["OpacityFilterFriendlyNPC"] = true,
		["UnitSpotlightColor"] = {
			["r"] = 0.8,
			["g"] = 0,
			["b"] = 0,
		},
		["StyleEnemyBarsClickThrough"] = false,
		["StyleFriendlyBarsClickThrough"] = false,
		["StatusTextRight"] = 7,
		["StyleFriendlyBarsOnPlayers"] = false,
		["ColorThreatSafe"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0.9019588232040405,
			["g"] = 0.588234007358551,
			["r"] = 0.05882339924573898,
		},
		["FrameVerticalPosition"] = 0.7,
		["HighlightFocustMode"] = 1,
		["CustomColorList"] = "",
		["WidgetEnableExternal"] = true,
		["EnemySubtext"] = "None",
		["WidgetQuestIcon"] = false,
		["FriendlySubtext"] = "None",
		["StyleEnemyMode"] = 1,
		["StatusTextCenterColor"] = true,
		["ColorFriendlyNameMode"] = 1,
		["TextColorGuildMember"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0.9999977946281433,
			["g"] = 0.6588220596313477,
			["r"] = 0.2352935969829559,
		},
		["ColorPartyAggro"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0.3999991118907929,
			["g"] = 0,
			["r"] = 0.9999977946281433,
		},
		["ColorBuffPurgeable"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0.9999977946281433,
			["g"] = 0.3999991118907929,
			["r"] = 0,
		},
		["HighlightTargetMode"] = 1,
		["WidgetBuffFilter"] = 2,
		["UnitSpotlightBarEnable"] = true,
		["WidgetBuffPurgeable"] = false,
		["WidgetThreatIndicator"] = false,
		["HeadlineEnemyColor"] = 4,
		["TextColorNeutral"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0.1058821231126785,
			["g"] = 0.7058808207511902,
			["r"] = 0.9882331490516663,
		},
		["ColorFriendlyNPC"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0,
			["g"] = 0.9999977946281433,
			["r"] = 0,
		},
		["OpacityFilterNonPartyMembers"] = false,
		["StyleFriendlyBarsInstanceMode"] = false,
		["SpellIconEnable"] = true,
		["EnemyBarColorMode"] = "ByHealth",
		["WidgetAuraTrackMagic"] = true,
		["ScaleFunctionMode"] = "ByThreat",
		["TextColorFriendlyPlayer"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0.9999977946281433,
			["g"] = 0.6588220596313477,
			["r"] = 0.2352935969829559,
		},
		["WidgetRangeScaleOptions"] = {
			["y"] = 1,
			["x"] = 1,
			["offset"] = {
				["y"] = 0,
				["x"] = 0,
			},
		},
		["ColorEnemyNameMode"] = 1,
		["OpacityFullNoTarget"] = false,
		["HideAuraDuration"] = false,
		["StatusTextLeftColor"] = true,
		["WidgetAuraScaleOptions"] = {
			["y"] = 1,
			["x"] = 1,
			["offset"] = {
				["y"] = 0,
				["x"] = 0,
			},
		},
		["ColorRangeMelee"] = {
			["a"] = 0,
			["b"] = 0.9019588232040405,
			["g"] = 0.9019588232040405,
			["r"] = 0.9019588232040405,
		},
		["ColorHighHealth"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0.1999995559453964,
			["g"] = 0.9999977946281433,
			["r"] = 0,
		},
		["WidgetMaxRange"] = 40,
		["StyleHeadlineMiniMobs"] = true,
		["ColorRangeClose"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0.8235275745391846,
			["g"] = 0.8745079040527344,
			["r"] = 0.05490183830261231,
		},
		["ColorThreatTransition"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0,
			["g"] = 0.627449631690979,
			["r"] = 0.9999977946281433,
		},
		["HeadlineFriendlyColor"] = 4,
		["UseGlobalSet"] = false,
		["WidgetDebuffPriority"] = {
		},
		["EmphasizedAuraList"] = "",
		["StyleFriendlyBarsOnElite"] = false,
		["WidgetAbsorbIndicator"] = true,
		["WidgetComboPoints"] = false,
		["ColorHealthBarMode"] = 3,
		["StyleFriendlyBarsOnActive"] = true,
		["IntCastEnable"] = true,
		["WidgetEliteIndicator"] = true,
		["CastBarWidth"] = 1,
		["FriendlyBarColorMode"] = "ByHealth",
		["ColorRangeFar"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0,
			["g"] = 0.5019596815109253,
			["r"] = 0.9999977946281433,
		},
		["StyleHeadlineOutOfCombat"] = false,
		["HeadlineEnemySubtext"] = "RoleGuildLevel",
		["OpacityFilterList"] = "",
		["OpacityFilterMini"] = true,
		["HighlightFocusMode"] = 1,
		["TextStatusForceShadow"] = false,
		["TextColorPartyMember"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0.9999977946281433,
			["g"] = 0.6588220596313477,
			["r"] = 0.2352935969829559,
		},
		["ColorNormalSpellCast"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0,
			["g"] = 0.549018383026123,
			["r"] = 0.9882331490516663,
		},
		["ColorHostileNPC"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0,
			["g"] = 0,
			["r"] = 0.9999977946281433,
		},
		["ColorNeutral"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0,
			["g"] = 0.9999977946281433,
			["r"] = 0.9999977946281433,
		},
		["UnitSpotlightGlowEnable"] = true,
		["WidgetAuraTrackDisease"] = true,
		["AltShortening"] = false,
		["StyleForceBarsOnTargets"] = true,
		["ColorMouseover"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0.4313715994358063,
			["g"] = 0.4313715994358063,
			["r"] = 0.4313715994358063,
		},
		["ClassIconScaleOptions"] = {
			["y"] = 1,
			["x"] = 1,
			["offset"] = {
				["y"] = 0,
				["x"] = 0,
			},
		},
		["ColorGuildMember"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0.9999977946281433,
			["g"] = 0.6588220596313477,
			["r"] = 0.2352935969829559,
		},
		["ClassColorPartyMembers"] = false,
		["StyleFriendlyBarsNoTotem"] = false,
		["WidgetAuraTrackCurse"] = true,
		["FriendlyNameColorMode"] = "ByClass",
		["ScaleIgnoreInactive"] = false,
		["ColorPartyAggroBar"] = false,
		["UnitSpotlightScaleEnable"] = true,
		["TextUseBlizzardFont"] = false,
		["ThreatWarningMode"] = "Auto",
		["ColorPartyAggroText"] = false,
		["WidgetOffsetY"] = 0,
		["ScaleFiltered"] = 1,
		["OpacityFilterUntitledFriendlyNPC"] = false,
		["ScaleIgnoreNonEliteUnits"] = false,
		["ScaleTargetSpotlight"] = true,
		["HideCooldownSpiral"] = false,
		["OpacitySpotlightMouseover"] = true,
		["WidgetAuraAlignment"] = 3,
		["WidgetRangeScale"] = false,
		["OpacityFilterInactive"] = false,
		["BorderPandemic"] = 1,
		["CustomMouseoverColor"] = false,
		["ColorShowPartyAggro"] = true,
		["WidgetRangeUnits"] = 2,
		["ColorDangerGlowMode"] = 2,
		["EnemyAlphaSpotlightMode"] = "OnLowHealth",
		["OpacitySpotlightRaidMarked"] = true,
		["StatusTextCenter"] = 5,
		["SpacerSlots"] = 0,
		["TextHealthTextMode"] = 1,
		["FocusAsTarget"] = false,
		["UnitSpotlightOpacity"] = 1,
		["StyleFriendlyMode"] = 2,
		["OpacityFilterLookup"] = {
		},
		["ColorBuffEnrage"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0.1999995559453964,
			["g"] = 0,
			["r"] = 0.9999977946281433,
		},
		["WidgetAbsorbMode"] = 1,
		["StyleEnemyBarsOnNPC"] = false,
		["ColorRangeOOR"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0.0745096430182457,
			["g"] = 0.05490183830261231,
			["r"] = 0.9019588232040405,
		},
		["UnitSpotlightList"] = "",
		["HighHealthThreshold"] = 0.7,
		["OpacityFilterPartyMembers"] = false,
		["WidgetRangeIndicator"] = false,
		["WidgetOffsetX"] = 0,
		["EnemyStatusTextMode"] = "HealthFunctionPercent",
		["ColorAttackingOtherTank"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0.7843120098114014,
			["g"] = 0.6666651964187622,
			["r"] = 0.05882339924573898,
		},
		["ColorUnIntpellCast"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0.7647042274475098,
			["g"] = 0.7529395222663879,
			["r"] = 0.5137243866920471,
		},
		["StyleEnemyBarsOnPlayers"] = false,
		["WidgetComboPointsStyle"] = 2,
		["StyleHeadlineNeutral"] = false,
		["HighlightMouseoverMode"] = 1,
		["StatusTextRightColor"] = true,
		["OpacityFilterNeutralUnits"] = false,
		["ColorThreatWarning"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0,
			["g"] = 0,
			["r"] = 0.7999982237815857,
		},
		["WidgetDebuffStyle"] = 1,
		["CustomTargetColor"] = false,
		["TextNameColorMode"] = 1,
		["TextColorFriendlyNPC"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0.1450977176427841,
			["g"] = 0.8784294128417969,
			["r"] = 0.376469761133194,
		},
		["OpacityFilterEnemyNPC"] = false,
		["StatusTextLeft"] = 8,
		["StyleEnemyBarsNoMinions"] = false,
		["EmphasizedAuraLookup"] = {
		},
		["UnitSpotlightScale"] = 1.4,
		["ColorFriendlyPlayer"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0.9999977946281433,
			["g"] = 0,
			["r"] = 0,
		},
		["OpacityFilterLowLevelUnits"] = false,
		["ClassPartyIcon"] = false,
		["EnemyNameColorMode"] = "ByClass",
		["TextShowLevel"] = false,
		["ColorMediumHealth"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0,
			["g"] = 0.9999977946281433,
			["r"] = 0.9999977946281433,
		},
		["WidgetTargetHighlight"] = true,
		["WidgetDebuffTrackList"] = "",
		["ClassEnemyIcon"] = false,
		["WidgetAbsorbUnits"] = 1,
		["OpacityFiltered"] = 0,
		["OpacityTarget"] = 1,
		["WidgetDebuff"] = true,
		["OpacitySpotlight"] = 0.85,
		["AdvancedEnableUnitCache"] = true,
		["TextColorHostileNPC"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0.1254899203777313,
			["g"] = 0.1999995559453964,
			["r"] = 0.9999977946281433,
		},
		["ThreatGlowEnable"] = false,
		["WidgetBuffEnrage"] = false,
		["TextShowServerIndicator"] = true,
		["TextColorHostilePlayer"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0.1254899203777313,
			["g"] = 0.1999995559453964,
			["r"] = 0.9999977946281433,
		},
		["WidgetAuraTrackPoison"] = true,
		["ScaleIgnoreNeutralUnits"] = false,
		["ColorLowHealth"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0,
			["g"] = 0,
			["r"] = 0.9999977946281433,
		},
		["CustomColorLookup"] = {
		},
		["WidgetComboPointsScaleOptions"] = {
			["y"] = 1,
			["x"] = 1,
			["offset"] = {
				["y"] = 0,
				["x"] = 0,
			},
		},
		["HeadlineFriendlySubtext"] = "RoleGuildLevel",
		["ScaleSpotlightMode"] = 2,
		["WidgetTotemIcon"] = false,
		["ColorTapped"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0.4313715994358063,
			["g"] = 0.4313715994358063,
			["r"] = 0.4313715994358063,
		},
		["HighlightFocusScale"] = {
			["y"] = 1,
			["x"] = 1,
			["offset"] = {
				["y"] = 0,
				["x"] = 0,
			},
		},
		["HighlightTargetScale"] = {
			["y"] = 1,
			["x"] = 1,
			["offset"] = {
				["y"] = 0,
				["x"] = 0,
			},
		},
		["OpacitySpotlightSpell"] = false,
		["WidgetThreatPercentage"] = false,
		["WidgetAllAuras"] = false,
		["ColorEnemyBarMode"] = 1,
		["EmphasizedUnique"] = true,
		["WidgetMyBuff"] = true,
		["ScaleStandard"] = 0.75,
		["WidgetAuraTrackDispelFriendly"] = true,
		["WidgetMyDebuff"] = true,
		["FriendlyAlphaSpotlightMode"] = "OnLowHealth",
		["TextColorElite"] = {
			["a"] = 0.5019596815109253,
			["b"] = 0.3019601106643677,
			["g"] = 0.7019592523574829,
			["r"] = 0.9019588232040405,
		},
		["StyleEnemyBarsOnActive"] = false,
		["ColorPartyAggroGlow"] = false,
		["ColorHostilePlayer"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0,
			["g"] = 0,
			["r"] = 0.9999977946281433,
		},
		["CustomFocusColor"] = false,
		["FriendlyStatusTextMode"] = "HealthFunctionPercent",
		["ScaleMouseoverSpotlight"] = true,
		["EmphasizedAuraPriority"] = {
		},
		["LowHealthThreshold"] = 0.3,
		["WidgetRangeMax"] = 40,
		["StyleFriendlyBarsNoMinions"] = false,
		["TextColorNormal"] = {
			["a"] = 0.3999991118907929,
			["b"] = 0.6509789824485779,
			["g"] = 0.6509789824485779,
			["r"] = 0.6509789824485779,
		},
		["ColorIntpellCast"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0,
			["g"] = 0,
			["r"] = 0.9999977946281433,
		},
		["WidgetDebuffLookup"] = {
		},
		["BorderBuffPurgeable"] = 1,
		["ColorPandemic"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0.1490192860364914,
			["g"] = 0.1490192860364914,
			["r"] = 0.9019588232040405,
		},
		["AuraScale"] = 1,
		["ColorPartyMember"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0.9999977946281433,
			["g"] = 0.6588220596313477,
			["r"] = 0.2352935969829559,
		},
		["FriendlyHeadlineColor"] = "ByClass",
		["ColorRangeMid"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0,
			["g"] = 0.8666647672653198,
			["r"] = 0.03529404103755951,
		},
		["EnemyHeadlineColor"] = "ByClass",
		["ScaleSpotlight"] = 1,
		["CastbarDurationMode"] = "None",
		["ColorFocus"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0.4313715994358063,
			["g"] = 0.4313715994358063,
			["r"] = 0.4313715994358063,
		},
		["TextColorBoss"] = {
			["a"] = 0.7999982237815857,
			["b"] = 0.1019605621695519,
			["g"] = 0.8509784936904907,
			["r"] = 0.9999977946281433,
		},
		["ThreatMode"] = 1,
		["UnitSpotlightOpacityEnable"] = true,
		["WidgetRangeStyle"] = 1,
		["ScaleCastingSpotlight"] = true,
		["StyleFriendlyBarsOnNPC"] = false,
		["WidgetDebuffFilter"] = 2,
		["HideAuraInHeadline"] = false,
	},
	["profiles"] = {
		["DMG"] = "ff007ffe",
		["Default"] = "FFFFFFFF",
		["Healer"] = "ff007ffe",
	},
	["HubPanelProfileDMG"] = {
		["TextShowOnlyOnActive"] = false,
		["WidgetAuraSort"] = 1,
		["TextShowOnlyOnTargets"] = false,
		["ColorFriendlyBarMode"] = 1,
		["FrameBarWidth"] = 1,
		["UnitSpotlightLookup"] = {
		},
		["EnableOffTankHighlight"] = false,
		["BorderBuffEnrage"] = 1,
		["OpacityFilterNonElite"] = false,
		["Theme"] = "Neon",
		["SpellCastEnableFriendly"] = false,
		["WidgetPandemic"] = false,
		["OpacityFilterPlayers"] = false,
		["StyleEnemyBarsInstanceMode"] = false,
		["ColorFriendlyStatusTextMode"] = 1,
		["HighlightMouseoverScale"] = {
			["y"] = 1,
			["x"] = 1,
			["offset"] = {
				["y"] = 0,
				["x"] = 0,
			},
		},
		["ColorTarget"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0.4313715994358063,
			["g"] = 0.4313715994358063,
			["r"] = 0.4313715994358063,
		},
		["ColorEnemyStatusTextMode"] = 1,
		["WidgetRangeMode"] = 1,
		["OpacityNonTarget"] = 0.7,
		["EmphasizedSlots"] = 1,
		["FilterScaleLock"] = false,
		["StyleEnemyBarsOnElite"] = true,
		["StyleEnemyBarsNoTotem"] = false,
		["IntCastWhoEnable"] = true,
		["OpacityFilterFriendlyNPC"] = true,
		["UnitSpotlightColor"] = {
			["r"] = 0.8,
			["g"] = 0,
			["b"] = 0,
		},
		["StyleEnemyBarsClickThrough"] = false,
		["StyleFriendlyBarsClickThrough"] = false,
		["StatusTextRight"] = 7,
		["StyleFriendlyBarsOnPlayers"] = false,
		["ColorThreatSafe"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0.9019588232040405,
			["g"] = 0.588234007358551,
			["r"] = 0.05882339924573898,
		},
		["FrameVerticalPosition"] = 0.7,
		["HighlightFocustMode"] = 1,
		["CustomColorList"] = "",
		["WidgetEnableExternal"] = true,
		["WidgetBuffEnrage"] = false,
		["WidgetQuestIcon"] = false,
		["EnemySubtext"] = "None",
		["FriendlySubtext"] = "None",
		["StatusTextCenterColor"] = true,
		["ColorFriendlyNameMode"] = 1,
		["TextColorGuildMember"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0.9999977946281433,
			["g"] = 0.6588220596313477,
			["r"] = 0.2352935969829559,
		},
		["ColorPartyAggro"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0.3999991118907929,
			["g"] = 0,
			["r"] = 0.9999977946281433,
		},
		["StyleEnemyMode"] = 1,
		["HighlightTargetMode"] = 1,
		["WidgetBuffFilter"] = 1,
		["UnitSpotlightBarEnable"] = true,
		["WidgetBuffPurgeable"] = false,
		["WidgetThreatIndicator"] = false,
		["HeadlineEnemyColor"] = 4,
		["TextColorNeutral"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0.1058821231126785,
			["g"] = 0.7058808207511902,
			["r"] = 0.9882331490516663,
		},
		["WidgetMaxRange"] = 40,
		["ColorEnemyNameMode"] = 1,
		["StyleFriendlyBarsInstanceMode"] = false,
		["ColorFriendlyNPC"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0,
			["g"] = 0.9999977946281433,
			["r"] = 0,
		},
		["SpellIconEnable"] = true,
		["WidgetAuraTrackMagic"] = true,
		["ScaleFunctionMode"] = "ByThreat",
		["TextColorFriendlyPlayer"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0.9999977946281433,
			["g"] = 0.6588220596313477,
			["r"] = 0.2352935969829559,
		},
		["EnemyBarColorMode"] = "ByHealth",
		["OpacityFilterNonPartyMembers"] = false,
		["OpacityFullNoTarget"] = false,
		["CastbarDurationMode"] = "None",
		["StatusTextLeftColor"] = true,
		["WidgetRangeScaleOptions"] = {
			["y"] = 1,
			["x"] = 1,
			["offset"] = {
				["y"] = 0,
				["x"] = 0,
			},
		},
		["StyleFriendlyBarsNoTotem"] = false,
		["ColorHighHealth"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0.1999995559453964,
			["g"] = 0.9999977946281433,
			["r"] = 0,
		},
		["WidgetAuraScaleOptions"] = {
			["y"] = 1,
			["x"] = 1,
			["offset"] = {
				["y"] = 0,
				["x"] = 0,
			},
		},
		["StyleHeadlineMiniMobs"] = true,
		["StatusTextCenter"] = 5,
		["ColorPartyMember"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0.9999977946281433,
			["g"] = 0.6588220596313477,
			["r"] = 0.2352935969829559,
		},
		["HeadlineFriendlyColor"] = 4,
		["UseGlobalSet"] = false,
		["WidgetDebuffPriority"] = {
		},
		["EmphasizedAuraList"] = "",
		["StyleFriendlyBarsOnElite"] = false,
		["StyleFriendlyBarsNoMinions"] = false,
		["WidgetComboPoints"] = true,
		["ColorHealthBarMode"] = 3,
		["StyleFriendlyBarsOnActive"] = false,
		["IntCastEnable"] = true,
		["WidgetEliteIndicator"] = true,
		["OpacityFilterList"] = "",
		["FriendlyBarColorMode"] = "ByHealth",
		["ColorRangeFar"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0,
			["g"] = 0.5019596815109253,
			["r"] = 0.9999977946281433,
		},
		["StyleHeadlineOutOfCombat"] = false,
		["HeadlineEnemySubtext"] = "RoleGuildLevel",
		["ColorRangeOOR"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0.0745096430182457,
			["g"] = 0.05490183830261231,
			["r"] = 0.9019588232040405,
		},
		["ColorBuffPurgeable"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0.9999977946281433,
			["g"] = 0.3999991118907929,
			["r"] = 0,
		},
		["WidgetRangeMax"] = 40,
		["ColorRangeMelee"] = {
			["a"] = 0,
			["b"] = 0.9019588232040405,
			["g"] = 0.9019588232040405,
			["r"] = 0.9019588232040405,
		},
		["TextColorPartyMember"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0.9999977946281433,
			["g"] = 0.6588220596313477,
			["r"] = 0.2352935969829559,
		},
		["ColorNormalSpellCast"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0,
			["g"] = 0.549018383026123,
			["r"] = 0.9882331490516663,
		},
		["ColorHostileNPC"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0,
			["g"] = 0,
			["r"] = 0.9999977946281433,
		},
		["AltShortening"] = false,
		["UnitSpotlightGlowEnable"] = true,
		["WidgetAuraTrackDisease"] = true,
		["ScaleMouseoverSpotlight"] = true,
		["StyleForceBarsOnTargets"] = true,
		["TextStatusForceShadow"] = false,
		["ClassIconScaleOptions"] = {
			["y"] = 1,
			["x"] = 1,
			["offset"] = {
				["y"] = 0,
				["x"] = 0,
			},
		},
		["ColorGuildMember"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0.9999977946281433,
			["g"] = 0.6588220596313477,
			["r"] = 0.2352935969829559,
		},
		["ClassColorPartyMembers"] = false,
		["ColorRangeClose"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0.8235275745391846,
			["g"] = 0.8745079040527344,
			["r"] = 0.05490183830261231,
		},
		["StyleEnemyBarsOnActive"] = true,
		["ColorPartyAggroBar"] = false,
		["ColorFriendlyPlayer"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0.9999977946281433,
			["g"] = 0,
			["r"] = 0,
		},
		["HeadlineFriendlySubtext"] = "RoleGuildLevel",
		["EmphasizedUnique"] = true,
		["UnitSpotlightScaleEnable"] = true,
		["ThreatWarningMode"] = "Auto",
		["ColorPartyAggroText"] = false,
		["WidgetOffsetY"] = 0,
		["ScaleFiltered"] = 0.75,
		["OpacityFilterUntitledFriendlyNPC"] = false,
		["ScaleIgnoreNonEliteUnits"] = false,
		["ScaleTargetSpotlight"] = true,
		["HideCooldownSpiral"] = false,
		["WidgetAuraAlignment"] = 3,
		["OpacitySpotlightMouseover"] = true,
		["WidgetRangeScale"] = false,
		["UnitSpotlightList"] = "",
		["BorderPandemic"] = 1,
		["CustomMouseoverColor"] = false,
		["ColorShowPartyAggro"] = false,
		["WidgetRangeUnits"] = 2,
		["StyleEnemyBarsOnNPC"] = false,
		["EnemyAlphaSpotlightMode"] = "OnLowHealth",
		["OpacitySpotlightRaidMarked"] = true,
		["UnitSpotlightOpacity"] = 1,
		["HighlightFocusMode"] = 1,
		["WidgetAllAuras"] = false,
		["FocusAsTarget"] = false,
		["ClassPartyIcon"] = false,
		["StyleFriendlyMode"] = 2,
		["ColorHostilePlayer"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0,
			["g"] = 0,
			["r"] = 0.9999977946281433,
		},
		["ColorBuffEnrage"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0.1999995559453964,
			["g"] = 0,
			["r"] = 0.9999977946281433,
		},
		["HighlightTargetScale"] = {
			["y"] = 1,
			["x"] = 1,
			["offset"] = {
				["y"] = 0,
				["x"] = 0,
			},
		},
		["TextUseBlizzardFont"] = false,
		["ColorAttackingOtherTank"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0.7843120098114014,
			["g"] = 0.6666651964187622,
			["r"] = 0.05882339924573898,
		},
		["ColorDangerGlowMode"] = 2,
		["StatusTextRightColor"] = true,
		["OpacityFilterPartyMembers"] = false,
		["AdvancedEnableUnitCache"] = true,
		["WidgetOffsetX"] = 0,
		["EnemyStatusTextMode"] = "HealthFunctionPercent",
		["OpacityFilterMini"] = true,
		["ColorUnIntpellCast"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0.7647042274475098,
			["g"] = 0.7529395222663879,
			["r"] = 0.5137243866920471,
		},
		["WidgetComboPointsScaleOptions"] = {
			["y"] = 1,
			["x"] = 1,
			["offset"] = {
				["y"] = 0,
				["x"] = 0,
			},
		},
		["SpacerSlots"] = 0,
		["StyleHeadlineNeutral"] = false,
		["HighlightMouseoverMode"] = 1,
		["FriendlyStatusTextMode"] = "HealthFunctionPercent",
		["OpacityFilterNeutralUnits"] = false,
		["CustomColorLookup"] = {
		},
		["WidgetDebuffStyle"] = 1,
		["CustomTargetColor"] = false,
		["StyleEnemyBarsNoMinions"] = false,
		["TextColorFriendlyNPC"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0.1450977176427841,
			["g"] = 0.8784294128417969,
			["r"] = 0.376469761133194,
		},
		["OpacityFilterEnemyNPC"] = false,
		["StatusTextLeft"] = 8,
		["TextNameColorMode"] = 1,
		["EmphasizedAuraLookup"] = {
		},
		["TextShowServerIndicator"] = true,
		["WidgetMyDebuff"] = true,
		["OpacityFilterLowLevelUnits"] = false,
		["TextHealthTextMode"] = 1,
		["EnemyNameColorMode"] = "ByClass",
		["OpacityFilterLookup"] = {
		},
		["ColorMediumHealth"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0,
			["g"] = 0.9999977946281433,
			["r"] = 0.9999977946281433,
		},
		["ThreatGlowEnable"] = false,
		["WidgetDebuffTrackList"] = "",
		["ClassEnemyIcon"] = false,
		["ScaleIgnoreNeutralUnits"] = false,
		["OpacityFiltered"] = 0,
		["OpacityTarget"] = 1,
		["ScaleIgnoreInactive"] = false,
		["OpacitySpotlight"] = 0.85,
		["WidgetTargetHighlight"] = true,
		["TextColorHostileNPC"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0.1254899203777313,
			["g"] = 0.1999995559453964,
			["r"] = 0.9999977946281433,
		},
		["WidgetRangeIndicator"] = false,
		["WidgetComboPointsStyle"] = 2,
		["UnitSpotlightScale"] = 1.4,
		["TextColorHostilePlayer"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0.1254899203777313,
			["g"] = 0.1999995559453964,
			["r"] = 0.9999977946281433,
		},
		["WidgetAuraTrackPoison"] = true,
		["FriendlyNameColorMode"] = "ByClass",
		["ColorLowHealth"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0,
			["g"] = 0,
			["r"] = 0.9999977946281433,
		},
		["ColorThreatWarning"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0,
			["g"] = 0,
			["r"] = 0.7999982237815857,
		},
		["StyleEnemyBarsOnPlayers"] = true,
		["WidgetDebuff"] = true,
		["OpacityFilterInactive"] = false,
		["WidgetTotemIcon"] = false,
		["ColorTapped"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0.4313715994358063,
			["g"] = 0.4313715994358063,
			["r"] = 0.4313715994358063,
		},
		["HighlightFocusScale"] = {
			["y"] = 1,
			["x"] = 1,
			["offset"] = {
				["y"] = 0,
				["x"] = 0,
			},
		},
		["WidgetAbsorbMode"] = 1,
		["OpacitySpotlightSpell"] = false,
		["WidgetAuraTrackCurse"] = true,
		["WidgetAbsorbUnits"] = 1,
		["ColorEnemyBarMode"] = 1,
		["HighHealthThreshold"] = 0.7,
		["WidgetMyBuff"] = false,
		["ScaleStandard"] = 0.75,
		["WidgetAuraTrackDispelFriendly"] = true,
		["CastBarWidth"] = 1,
		["FriendlyAlphaSpotlightMode"] = "None",
		["TextColorElite"] = {
			["a"] = 0.5019596815109253,
			["b"] = 0.3019601106643677,
			["g"] = 0.7019592523574829,
			["r"] = 0.9019588232040405,
		},
		["ScaleSpotlightMode"] = 2,
		["ColorPartyAggroGlow"] = false,
		["ColorMouseover"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0.4313715994358063,
			["g"] = 0.4313715994358063,
			["r"] = 0.4313715994358063,
		},
		["CustomFocusColor"] = false,
		["TextShowLevel"] = false,
		["ColorNeutral"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0,
			["g"] = 0.9999977946281433,
			["r"] = 0.9999977946281433,
		},
		["EmphasizedAuraPriority"] = {
		},
		["LowHealthThreshold"] = 0.3,
		["WidgetThreatPercentage"] = false,
		["WidgetAbsorbIndicator"] = true,
		["TextColorNormal"] = {
			["a"] = 0.3999991118907929,
			["b"] = 0.6509789824485779,
			["g"] = 0.6509789824485779,
			["r"] = 0.6509789824485779,
		},
		["ColorIntpellCast"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0,
			["g"] = 0,
			["r"] = 0.9999977946281433,
		},
		["WidgetDebuffLookup"] = {
		},
		["BorderBuffPurgeable"] = 1,
		["ColorPandemic"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0.1490192860364914,
			["g"] = 0.1490192860364914,
			["r"] = 0.9019588232040405,
		},
		["AuraScale"] = 1,
		["ColorThreatTransition"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0,
			["g"] = 0.627449631690979,
			["r"] = 0.9999977946281433,
		},
		["FriendlyHeadlineColor"] = "ByClass",
		["ColorRangeMid"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0,
			["g"] = 0.8666647672653198,
			["r"] = 0.03529404103755951,
		},
		["EnemyHeadlineColor"] = "ByClass",
		["ScaleSpotlight"] = 1,
		["HideAuraDuration"] = false,
		["ColorFocus"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0.4313715994358063,
			["g"] = 0.4313715994358063,
			["r"] = 0.4313715994358063,
		},
		["TextColorBoss"] = {
			["a"] = 0.7999982237815857,
			["b"] = 0.1019605621695519,
			["g"] = 0.8509784936904907,
			["r"] = 0.9999977946281433,
		},
		["ThreatMode"] = 1,
		["UnitSpotlightOpacityEnable"] = true,
		["WidgetRangeStyle"] = 1,
		["ScaleCastingSpotlight"] = true,
		["StyleFriendlyBarsOnNPC"] = false,
		["WidgetDebuffFilter"] = 2,
		["HideAuraInHeadline"] = false,
	},
	["HubPanelProfileDefault"] = {
		["TextShowOnlyOnActive"] = false,
		["WidgetAuraSort"] = 1,
		["TextShowOnlyOnTargets"] = false,
		["ColorFriendlyBarMode"] = 1,
		["FrameBarWidth"] = 1,
		["UnitSpotlightLookup"] = {
		},
		["EnableOffTankHighlight"] = false,
		["BorderBuffEnrage"] = 1,
		["OpacityFilterNonElite"] = false,
		["Theme"] = "Neon",
		["SpellCastEnableFriendly"] = false,
		["WidgetPandemic"] = false,
		["OpacityFilterPlayers"] = false,
		["StyleEnemyBarsInstanceMode"] = false,
		["ColorFriendlyStatusTextMode"] = 1,
		["HighlightMouseoverScale"] = {
			["y"] = 1,
			["x"] = 1,
			["offset"] = {
				["y"] = 0,
				["x"] = 0,
			},
		},
		["ColorTarget"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0.4313715994358063,
			["g"] = 0.4313715994358063,
			["r"] = 0.4313715994358063,
		},
		["ColorEnemyStatusTextMode"] = 1,
		["WidgetRangeMode"] = 1,
		["OpacityNonTarget"] = 0.7,
		["EmphasizedSlots"] = 1,
		["FilterScaleLock"] = false,
		["StyleEnemyBarsOnElite"] = true,
		["StyleEnemyBarsNoTotem"] = false,
		["IntCastWhoEnable"] = true,
		["OpacityFilterFriendlyNPC"] = false,
		["UnitSpotlightColor"] = {
			["r"] = 0.8,
			["g"] = 0,
			["b"] = 0,
		},
		["StyleEnemyBarsClickThrough"] = false,
		["StyleFriendlyBarsClickThrough"] = false,
		["StatusTextRight"] = 7,
		["StyleFriendlyBarsOnPlayers"] = false,
		["HideAuraInHeadline"] = false,
		["FrameVerticalPosition"] = 0.7,
		["HighlightFocustMode"] = 1,
		["CustomColorList"] = "",
		["WidgetEnableExternal"] = true,
		["WidgetDebuffFilter"] = 2,
		["WidgetQuestIcon"] = false,
		["EnemySubtext"] = "None",
		["FriendlySubtext"] = "None",
		["StatusTextCenterColor"] = true,
		["ColorFriendlyNameMode"] = 1,
		["TextColorGuildMember"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0.9999977946281433,
			["g"] = 0.6588220596313477,
			["r"] = 0.2352935969829559,
		},
		["WidgetBuffFilter"] = 1,
		["StyleEnemyMode"] = 1,
		["HighlightTargetMode"] = 1,
		["ColorPartyAggro"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0.3999991118907929,
			["g"] = 0,
			["r"] = 0.9999977946281433,
		},
		["UnitSpotlightBarEnable"] = true,
		["WidgetBuffPurgeable"] = false,
		["WidgetThreatIndicator"] = false,
		["HeadlineEnemyColor"] = 4,
		["TextColorNeutral"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0.1058821231126785,
			["g"] = 0.7058808207511902,
			["r"] = 0.9882331490516663,
		},
		["ColorFriendlyNPC"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0,
			["g"] = 0.9999977946281433,
			["r"] = 0,
		},
		["OpacityFilterNonPartyMembers"] = false,
		["StyleFriendlyBarsInstanceMode"] = false,
		["SpellIconEnable"] = true,
		["WidgetRangeScaleOptions"] = {
			["y"] = 1,
			["x"] = 1,
			["offset"] = {
				["y"] = 0,
				["x"] = 0,
			},
		},
		["WidgetAuraTrackMagic"] = true,
		["ScaleFunctionMode"] = "ByThreat",
		["TextColorFriendlyPlayer"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0.9999977946281433,
			["g"] = 0.6588220596313477,
			["r"] = 0.2352935969829559,
		},
		["EnemyBarColorMode"] = "ByThreat",
		["ColorEnemyNameMode"] = 1,
		["OpacityFullNoTarget"] = false,
		["CastbarDurationMode"] = "None",
		["StatusTextLeftColor"] = true,
		["WidgetAuraScaleOptions"] = {
			["y"] = 1,
			["x"] = 1,
			["offset"] = {
				["y"] = 0,
				["x"] = 0,
			},
		},
		["OpacityFilterMini"] = true,
		["ColorHighHealth"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0.1999995559453964,
			["g"] = 0.9999977946281433,
			["r"] = 0,
		},
		["StyleFriendlyBarsNoTotem"] = false,
		["StyleHeadlineMiniMobs"] = false,
		["WidgetMaxRange"] = 40,
		["ColorPartyMember"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0.9999977946281433,
			["g"] = 0.6588220596313477,
			["r"] = 0.2352935969829559,
		},
		["HeadlineFriendlyColor"] = 4,
		["AuraScale"] = 1,
		["WidgetDebuffPriority"] = {
		},
		["EmphasizedAuraList"] = "",
		["StyleFriendlyBarsOnElite"] = false,
		["WidgetAbsorbIndicator"] = true,
		["WidgetComboPoints"] = true,
		["ColorHealthBarMode"] = 3,
		["StyleFriendlyBarsOnActive"] = false,
		["IntCastEnable"] = true,
		["WidgetEliteIndicator"] = true,
		["ColorHostilePlayer"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0,
			["g"] = 0,
			["r"] = 0.9999977946281433,
		},
		["FriendlyBarColorMode"] = "ByReaction",
		["ColorRangeFar"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0,
			["g"] = 0.5019596815109253,
			["r"] = 0.9999977946281433,
		},
		["StyleHeadlineOutOfCombat"] = false,
		["HeadlineEnemySubtext"] = "RoleGuildLevel",
		["SpacerSlots"] = 0,
		["StyleFriendlyBarsNoMinions"] = false,
		["WidgetRangeMax"] = 40,
		["TextStatusForceShadow"] = false,
		["TextColorPartyMember"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0.9999977946281433,
			["g"] = 0.6588220596313477,
			["r"] = 0.2352935969829559,
		},
		["ColorNormalSpellCast"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0,
			["g"] = 0.549018383026123,
			["r"] = 0.9882331490516663,
		},
		["ColorHostileNPC"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0,
			["g"] = 0,
			["r"] = 0.9999977946281433,
		},
		["ColorRangeMelee"] = {
			["a"] = 0,
			["b"] = 0.9019588232040405,
			["g"] = 0.9019588232040405,
			["r"] = 0.9019588232040405,
		},
		["UnitSpotlightGlowEnable"] = true,
		["WidgetAuraTrackDisease"] = true,
		["UnitSpotlightOpacity"] = 1,
		["StyleForceBarsOnTargets"] = true,
		["TextShowLevel"] = false,
		["ClassIconScaleOptions"] = {
			["y"] = 1,
			["x"] = 1,
			["offset"] = {
				["y"] = 0,
				["x"] = 0,
			},
		},
		["ColorGuildMember"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0.9999977946281433,
			["g"] = 0.6588220596313477,
			["r"] = 0.2352935969829559,
		},
		["ClassColorPartyMembers"] = false,
		["StyleEnemyBarsOnActive"] = true,
		["ColorNeutral"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0,
			["g"] = 0.9999977946281433,
			["r"] = 0.9999977946281433,
		},
		["ColorMouseover"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0.4313715994358063,
			["g"] = 0.4313715994358063,
			["r"] = 0.4313715994358063,
		},
		["ScaleIgnoreInactive"] = false,
		["WidgetAuraTrackCurse"] = true,
		["FriendlyStatusTextMode"] = "HealthFunctionPercent",
		["TextUseBlizzardFont"] = false,
		["ThreatWarningMode"] = "Auto",
		["ColorPartyAggroText"] = false,
		["WidgetAuraTrackDispelFriendly"] = false,
		["ScaleFiltered"] = 0.75,
		["OpacityFilterUntitledFriendlyNPC"] = true,
		["ScaleIgnoreNonEliteUnits"] = false,
		["ScaleTargetSpotlight"] = true,
		["HideCooldownSpiral"] = false,
		["WidgetAuraAlignment"] = 1,
		["OpacityFilterList"] = "",
		["WidgetMyBuff"] = false,
		["UnitSpotlightList"] = "",
		["BorderPandemic"] = 1,
		["CustomMouseoverColor"] = false,
		["ColorShowPartyAggro"] = false,
		["WidgetRangeUnits"] = 2,
		["ColorDangerGlowMode"] = 2,
		["EnemyAlphaSpotlightMode"] = "ByThreat",
		["OpacitySpotlightRaidMarked"] = false,
		["FriendlyNameColorMode"] = "ByClass",
		["ThreatGlowEnable"] = true,
		["WidgetAllAuras"] = false,
		["FocusAsTarget"] = false,
		["ColorPartyAggroBar"] = false,
		["StyleFriendlyMode"] = 2,
		["OpacityFilterInactive"] = false,
		["ColorBuffEnrage"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0.1999995559453964,
			["g"] = 0,
			["r"] = 0.9999977946281433,
		},
		["HighlightTargetScale"] = {
			["y"] = 1,
			["x"] = 1,
			["offset"] = {
				["y"] = 0,
				["x"] = 0,
			},
		},
		["WidgetBuffEnrage"] = false,
		["StyleEnemyBarsOnNPC"] = false,
		["OpacitySpotlightMouseover"] = true,
		["WidgetRangeIndicator"] = false,
		["OpacityFilterPartyMembers"] = false,
		["AdvancedEnableUnitCache"] = true,
		["WidgetOffsetX"] = 0,
		["EnemyStatusTextMode"] = "HealthFunctionPercent",
		["WidgetThreatPercentage"] = false,
		["ColorUnIntpellCast"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0.7647042274475098,
			["g"] = 0.7529395222663879,
			["r"] = 0.5137243866920471,
		},
		["WidgetComboPointsScaleOptions"] = {
			["y"] = 1,
			["x"] = 1,
			["offset"] = {
				["y"] = 0,
				["x"] = 0,
			},
		},
		["OpacityFilterNeutralUnits"] = false,
		["StyleHeadlineNeutral"] = false,
		["HighlightMouseoverMode"] = 1,
		["CustomColorLookup"] = {
		},
		["ColorLowHealth"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0,
			["g"] = 0,
			["r"] = 0.9999977946281433,
		},
		["WidgetTargetHighlight"] = true,
		["WidgetDebuffStyle"] = 1,
		["CustomTargetColor"] = false,
		["StyleEnemyBarsNoMinions"] = false,
		["TextColorFriendlyNPC"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0.1450977176427841,
			["g"] = 0.8784294128417969,
			["r"] = 0.376469761133194,
		},
		["OpacityFilterEnemyNPC"] = false,
		["StatusTextLeft"] = 8,
		["TextNameColorMode"] = 1,
		["EmphasizedAuraLookup"] = {
		},
		["TextShowServerIndicator"] = true,
		["ColorFriendlyPlayer"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0.9999977946281433,
			["g"] = 0,
			["r"] = 0,
		},
		["OpacityFilterLowLevelUnits"] = false,
		["ScaleSpotlightMode"] = 2,
		["EnemyNameColorMode"] = "ByClass",
		["OpacityFilterLookup"] = {
		},
		["ColorMediumHealth"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0,
			["g"] = 0.9999977946281433,
			["r"] = 0.9999977946281433,
		},
		["EmphasizedUnique"] = true,
		["WidgetDebuffTrackList"] = "",
		["ClassEnemyIcon"] = false,
		["OpacityFiltered"] = 0,
		["OpacitySpotlight"] = 0.85,
		["OpacityTarget"] = 1,
		["WidgetMyDebuff"] = true,
		["WidgetAbsorbUnits"] = 1,
		["StatusTextRightColor"] = true,
		["TextColorHostileNPC"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0.1254899203777313,
			["g"] = 0.1999995559453964,
			["r"] = 0.9999977946281433,
		},
		["ScaleIgnoreNeutralUnits"] = false,
		["WidgetComboPointsStyle"] = 2,
		["UnitSpotlightScale"] = 1.4,
		["TextColorHostilePlayer"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0.1254899203777313,
			["g"] = 0.1999995559453964,
			["r"] = 0.9999977946281433,
		},
		["WidgetAuraTrackPoison"] = true,
		["HeadlineFriendlySubtext"] = "RoleGuildLevel",
		["WidgetDebuff"] = true,
		["HighHealthThreshold"] = 0.7,
		["StyleEnemyBarsOnPlayers"] = true,
		["ColorThreatWarning"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0,
			["g"] = 0,
			["r"] = 0.7999982237815857,
		},
		["ColorAttackingOtherTank"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0.7843120098114014,
			["g"] = 0.6666651964187622,
			["r"] = 0.05882339924573898,
		},
		["WidgetTotemIcon"] = false,
		["ColorTapped"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0.4313715994358063,
			["g"] = 0.4313715994358063,
			["r"] = 0.4313715994358063,
		},
		["HighlightFocusScale"] = {
			["y"] = 1,
			["x"] = 1,
			["offset"] = {
				["y"] = 0,
				["x"] = 0,
			},
		},
		["WidgetAbsorbMode"] = 1,
		["OpacitySpotlightSpell"] = false,
		["ColorThreatSafe"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0.9019588232040405,
			["g"] = 0.588234007358551,
			["r"] = 0.05882339924573898,
		},
		["TextHealthTextMode"] = 1,
		["ColorEnemyBarMode"] = 1,
		["ColorBuffPurgeable"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0.9999977946281433,
			["g"] = 0.3999991118907929,
			["r"] = 0,
		},
		["WidgetRangeScale"] = false,
		["ScaleStandard"] = 0.76,
		["WidgetOffsetY"] = 0,
		["UnitSpotlightScaleEnable"] = true,
		["FriendlyAlphaSpotlightMode"] = "None",
		["TextColorElite"] = {
			["a"] = 0.5019596815109253,
			["b"] = 0.3019601106643677,
			["g"] = 0.7019592523574829,
			["r"] = 0.9019588232040405,
		},
		["ClassPartyIcon"] = false,
		["ColorPartyAggroGlow"] = true,
		["CastBarWidth"] = 1,
		["CustomFocusColor"] = false,
		["ColorRangeClose"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0.8235275745391846,
			["g"] = 0.8745079040527344,
			["r"] = 0.05490183830261231,
		},
		["AltShortening"] = false,
		["EmphasizedAuraPriority"] = {
		},
		["LowHealthThreshold"] = 0.3,
		["HighlightFocusMode"] = 1,
		["ScaleMouseoverSpotlight"] = true,
		["TextColorNormal"] = {
			["a"] = 0.3999991118907929,
			["b"] = 0.6509789824485779,
			["g"] = 0.6509789824485779,
			["r"] = 0.6509789824485779,
		},
		["ColorIntpellCast"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0,
			["g"] = 0,
			["r"] = 0.9999977946281433,
		},
		["WidgetDebuffLookup"] = {
		},
		["BorderBuffPurgeable"] = 1,
		["ColorPandemic"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0.1490192860364914,
			["g"] = 0.1490192860364914,
			["r"] = 0.9019588232040405,
		},
		["UseGlobalSet"] = false,
		["ColorThreatTransition"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0,
			["g"] = 0.627449631690979,
			["r"] = 0.9999977946281433,
		},
		["FriendlyHeadlineColor"] = "ByReaction",
		["ColorRangeMid"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0,
			["g"] = 0.8666647672653198,
			["r"] = 0.03529404103755951,
		},
		["EnemyHeadlineColor"] = "ByReaction",
		["ScaleSpotlight"] = 1,
		["HideAuraDuration"] = false,
		["ColorFocus"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0.4313715994358063,
			["g"] = 0.4313715994358063,
			["r"] = 0.4313715994358063,
		},
		["TextColorBoss"] = {
			["a"] = 0.7999982237815857,
			["b"] = 0.1019605621695519,
			["g"] = 0.8509784936904907,
			["r"] = 0.9999977946281433,
		},
		["ThreatMode"] = 1,
		["UnitSpotlightOpacityEnable"] = true,
		["WidgetRangeStyle"] = 1,
		["ScaleCastingSpotlight"] = false,
		["StyleFriendlyBarsOnNPC"] = false,
		["StatusTextCenter"] = 5,
		["ColorRangeOOR"] = {
			["a"] = 0.9999977946281433,
			["b"] = 0.0745096430182457,
			["g"] = 0.05490183830261231,
			["r"] = 0.9019588232040405,
		},
	},
}

**Comment by Luxocracy** [comment]
I figured out what was going on, the subtext wasn't updating its content properly when it automatically swapped between styles(Headline/Bar mode) as opposed to when it's changed in the settings.

So this should be fixed in the latest release.

**Comment by yah467958** [comment]
Awesome to hear that! Good work :)

**Comment by yah467958** [comment]
Hello once again!

After latest update unfortunately problem is still there :<
And so far what i noticed is that if i target someone level 
magically disappears

**Comment by Luxocracy** [comment]
Well targeting or mousing over a unit will trigger an update of the plates, so it makes sense that it goes away if it just simply isn't updating correctly.

But I just can't seem to recreate this issue any more in the latest update. However, while looking at the code I can only think of one other possible cause of what you are describing. So I'll create a new release with that fix and hopefully this goes away for good.

**Comment by yah467958** [comment]
Eureka! 

Finally level gone 💃 Awesome job mate!
