### ISSUE TITLE
Threat Update Error

### ISSUE THREAD

**Issue by Chzconey** [Luxocracy/NeatPlates#197]
Date: 2020-03-14 12:54:08
ID: 3
Error occured in: Global
Count: 15
Message: ..\AddOns\NeatPlatesHub\functions\Style.lua line 27:
   attempt to compare two nil values
Debug:
   (tail call): ?
   NeatPlatesHub\functions\Style.lua:27:
      NeatPlatesHub\functions\Style.lua:17
   NeatPlatesHub\functions\Style.lua:172: SetStyle()
   NeatPlates\NeatPlatesCore.lua:480:
      NeatPlates\NeatPlatesCore.lua:478
   NeatPlates\NeatPlatesCore.lua:513:
      NeatPlates\NeatPlatesCore.lua:501
   NeatPlates\NeatPlatesCore.lua:646:
      NeatPlates\NeatPlatesCore.lua:642
   NeatPlates\NeatPlatesCore.lua:1797: THREAT_UPDATE()
   NeatPlates\NeatPlatesUtility.lua:27:
      NeatPlates\NeatPlatesUtility.lua:27
   [C]: ?
   ...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:29:
      ...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25
   ...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: Fire()
   ...BM-Core\Libs\LibThreatClassic2\LibThreatClassic2.lua:806: ThreatUpdatedForUnit()
   ...BM-Core\Libs\LibThreatClassic2\LibThreatClassic2.lua:787: ThreatUpdated()
   ...ore\Libs\LibThreatClassic2\ThreatClassModuleCore.lua:1113: AddTargetThreat()
   ...ore\Libs\LibThreatClassic2\ThreatClassModuleCore.lua:1131: AddThreat()
   ...s\LibThreatClassic2\ClassModules\Classic\Warrior.lua:161: ?()
   ...ore\Libs\LibThreatClassic2\ThreatClassModuleCore.lua:1172: ?()
   ...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119:
      ...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119
   [C]: ?
   ...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:29:
      ...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25
   ...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: Fire()
   ...\AddOns\DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua:120:
      ...\AddOns\DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua:119
Locals:
None
AddOns:

**Comment by Luxocracy** [comment]
I pushed a new release that I believe should stop this error from occurring, should be available shortly on curse.

**Comment by Chzconey** [comment]
Ok I have another error if not fixed

Date: 2020-03-14 14:07:15
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\NeatPlates\NeatPlatesCore.lua line 505:
   bad argument #1 to 'pairs' (table expected, got nil)
Debug:
   (tail call): ?
   [C]: ?
   NeatPlates\NeatPlatesCore.lua:505:
      NeatPlates\NeatPlatesCore.lua:501
   NeatPlates\NeatPlatesCore.lua:646:
      NeatPlates\NeatPlatesCore.lua:642
   NeatPlates\NeatPlatesCore.lua:1797: THREAT_UPDATE()
   NeatPlates\NeatPlatesUtility.lua:27:
      NeatPlates\NeatPlatesUtility.lua:27
   [C]: ?
   ...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:29:
      ...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25
   ...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: Fire()
   ...BM-Core\Libs\LibThreatClassic2\LibThreatClassic2.lua:806: ThreatUpdatedForUnit()
   ...BM-Core\Libs\LibThreatClassic2\LibThreatClassic2.lua:787: ThreatUpdated()
   ...ore\Libs\LibThreatClassic2\ThreatClassModuleCore.lua:1113: AddTargetThreat()
   ...ore\Libs\LibThreatClassic2\ThreatClassModuleCore.lua:1131: AddThreat()
   ...ore\Libs\LibThreatClassic2\ThreatClassModuleCore.lua:995: parseGain()
   ...ore\Libs\LibThreatClassic2\ThreatClassModuleCore.lua:549: handler()
   ...ore\Libs\LibThreatClassic2\ThreatClassModuleCore.lua:702: ?()
   ...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119:
      ...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119
   [C]: ?
   ...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:29:
      ...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25
   ...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: Fire()
   ...\AddOns\DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua:120:
      ...\AddOns\DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua:119
Locals:
None

**Comment by Chzconey** [comment]
Will check for update though to see if its fixed
